name: Docker Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: docker/setup-docker-action@v4
        with:
          rootless: true

      - name: Build
        run: |
          docker build -t luabot:latest .
